### PR TITLE
Switch to picocolors

### PR DESCRIPTION
**Pull request by XhmikosR**
This is my suggestion.

Requires the previous PRs to be merged so ping me to rebase when needed.

Feel free to skip this if you find the current solution fine :)

### CODE REVIEW

**Comment by C-Lodder** [comment]
All other PRs merged.

I just remembered that one of the reasons I used these colour methods was that I think sublime wasn't displaying the colours.

**Comment by XhmikosR** [comment]
@C-Lodder can you try this branch please? Also, please verify that the colors I used are the correct ones because I'm not 100% sure they are correct since it was like magic to me :P

**Comment by C-Lodder** [comment]
Thanks @XhmikosR

**Comment by XhmikosR** [comment]
Thanks for merging! Don't forget to make a new release please :)

**Pull request merged**
