### PR TITLE
README.md: Markdown tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@C-Lodder it seems you have both Travis CI org and com added to the repo. This PR switches to the com instance. I suggest you remove the org instance from the repo and just keep the app.

**Comment by C-Lodder** [comment]
@XhmikosR I've merged your other PR. Can you fetch and push to retrigger the build with the updated config please

**Comment by XhmikosR** [comment]
Done. Just FYI you could also do it.

**Comment by XhmikosR** [comment]
Still seeing 2 hooks

**Comment by XhmikosR** [comment]
We can just use GitHub Actions CI and remove everything Travis related

**Comment by XhmikosR** [comment]
Anyway just merge this and I'll make a GH Actions PR.

**Comment by C-Lodder** [comment]
Cheers

**Pull request merged**
